inputSet:
  name: Build_apisix_ingress_controller_1695760125497-pr-trigger-input-set
  identifier: Build_apisix_ingress_controller_1695760125497prtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_apisix_ingress_controller_1695760125497
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
